# PracticaFinal/.github/workflows/build.yml

name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install frontend dependencies
      working-directory: ./front
      run: |
        npm cache clean --force
        npm install
      
    - name: Run frontend linting
      working-directory: ./front
      run: npm run lint
      
    - name: Run frontend tests
      working-directory: ./front
      run: npm test
      continue-on-error: true
      
    - name: Build frontend
      working-directory: ./front
      run: npm run build 

    - name: Deploy frontend to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./front/dist

  build-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install backend dependencies
      working-directory: ./back
      run: npm ci
      
    - name: Run backend tests
      working-directory: ./back
      run: npm test
      continue-on-error: true
